### PR TITLE
lettuce:overlay:lineage-sdk:values

### PR DESCRIPTION
**Pull request by hpnightowl**
* error: xml parser error: not well-formed (invalid token).

### CODE REVIEW

**Comment by ghostrider-reborn** [comment]
now tell me how is this XML **not** deformed?
https://i.imgur.com/XwAMCWv.png

**Comment by ghostrider-reborn** [comment]
fix this please
https://i.imgur.com/XwAMCWv.png

**Comment by hpnightowl** [comment]
ok my mistake

**Comment by hpnightowl** [comment]
edit it  according to you i am lazy.

**Comment by Akianonymus** [comment]
> fix this please
> https://i.imgur.com/XwAMCWv.png

lmao pro

**Pull request merged**
