### PR TITLE
lettuce: rootdir: Resolve dac_override for tftp_server

### PR DESCRIPTION
**Pull request by YourDeathWish**

### CODE REVIEW

**Comment by YourDeathWish** [comment]
my fucking mistake

**Comment by ghostrider-reborn** [comment]
> my fucking mistake

chill bro you could've just rebased and force-pushed to your fork, it'd get reflected here :)

**Comment by Akianonymus** [comment]
lettuce doesn't even use tftp server, lol

**Comment by ghostrider-reborn** [comment]
> lettuce doesn't even use tftp server, lol

meh it was there in crackling dump so added it

**Pull request closed without merging**
